# Docker-Compose document
# Ref : https://docs.docker.com/compose/compose-file/

services:
  grafana:
    image: grafana/grafana
    container_name: docker-grafana-${GF_VERSION}_${PROJECT_NAME}
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - bisa
    environment:
      - GF_SERVER_PROTOCOL=http
      - GF_SERVER_HTTP_ADDR=0.0.0.0
      - GF_SERVER_HTTP_PORT=3000
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=adminpsw
      - GF_PATHS_CONFIG=/usr/share/grafana/host/grafana.ini
    volumes:
      - ${GF_DATA_VOLUME}:/var/lib/grafana
      - ${GF_SHELL_VOLUME}:/usr/share/grafana/shell
      - ${GF_CONFIG_DIR}/grafana.ini:/usr/share/grafana/host/grafana.ini:ro
      - ${GF_CERTS_DIR}:/usr/share/grafana/host/certs:ro

networks:
  bisa:
    driver: bridge
